### ISSUE TITLE
Question about capctured context in AsyncCommand

### ISSUE THREAD

**Issue by nschoenberg** [brminnick/AsyncAwaitBestPractices#35]
Hi,

wondering why the default is false for continueOnCapturedContext. I mean, I know thats in general the better choice. But most of commands do something with UI, right? For Example Updating a ListView, showing a busy indicator, etc. Im not very deep in Xamarin Forms binding Engine and not sure about thread synchronization in case the AsyncCommand starts something that runs next to the main thread (And yea, theres not always a new thread, but can).

When you think of most common UI cases, is false a good default? Thanks in advance

https://github.com/brminnick/AsyncAwaitBestPractices/blob/3157c462610d2ba02c70b207f4f9947d8f13c5ed/Src/AsyncAwaitBestPractices.MVVM/AsyncCommand.cs#L29

**Comment by brminnick** [comment]
Honestly, `continueOnCapturedContext` shouldn't even be an option; it should always be `false` because `ConfigureAwait` only impacts the code that executes after `Func<Task> _execute ` finishes and no code executes after `_execute`.

When `AsyncCommand` is executed, it calls `_execute .SafeFireAndForget`

In `SafeFireAndForget`, there is no code that executes following the completion of the `Task`:
https://github.com/brminnick/AsyncAwaitBestPractices/blob/3157c462610d2ba02c70b207f4f9947d8f13c5ed/Src/AsyncAwaitBestPractices/SafeFireAndForgetExtensions.cs#L81

If the default was `true`, .NET would switching back to the calling thread after executing the `Task`, which, in the context of `SafeFireAndForget`, it would be switching back to the calling thread only to return method finalizer. It's a needless context switch.
