### ISSUE TITLE
Parameter change does not invoke CanExecuteChanged

### ISSUE THREAD

**Issue by davidvanelk** [brminnick/AsyncAwaitBestPractices#88]
When the command parameter is updated, the `CanExecuteChanged`-event is not invoked due to missing link to `CommandManager.RequerySuggested`.
Working implementation could be something like:

```
        public event EventHandler? CanExecuteChanged
        {
            add => CommandManager.RequerySuggested += value;
            remove => CommandManager.RequerySuggested -= value;
        }
```

The above code will execute `CanExecute()` after the command parameter changed, but is only available in WPF projects. Maybe creating a WPF lib could fix that?

**Comment by brminnick** [comment]
Hi @andrekiba,

By design, the user is required to call `RaiseCanExecuteChanged` whenever the CommandParameter changes, and marshall it to the UI thread, if necessary.

Every UI Framework (WPF, UWP, Xamarin, etc) requires the update to be marshalled to the main thread, and each framework uses a different method of marshaling it, and we elected not to implement any platform-specific code in this library.

There's more information here in this discussion: https://github.com/brminnick/AsyncAwaitBestPractices/issues/88
